### ISSUE TITLE
Progress temp directory exceeded limit for a long running job causing spark job to fail. 

### ISSUE THREAD

**Issue by kpratik16** [Azure/azure-event-hubs-spark#181]
- Spark Version: 2.1
- Spark-Eventhubs version: 2.1.5-SNAPSHOT

A long running spark job failed with following error:

```
17/10/14 07:37:10 INFO TaskSetManager: Lost task 1.2 in stage 114690.0 (TID 2211875) on 10.0.0.18, executor 6: org.apache.hadoop.ipc.RemoteException (The directory item limit of /progressDir/noor3/fcmspark_temp is exceeded: limit=1048576 items=1048576
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.verifyMaxDirItems(FSDirectory.java:1131)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.addLastINode(FSDirectory.java:1176)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.addINode(FSDirectory.java:1037)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.addFile(FSDirectory.java:501)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInternal(FSNamesystem.java:2797)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2672)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2556)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:736)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:408)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2345)
```

**Comment by sabeegrewal** [comment]
Hey Pratik, thanks for reporting this 👍  Just a quick update: we're planning on removing the progress tracker and this will become a non-issue after. It'll be gone by end of 2018 Q1 for sure, but hopefully much sooner. I'll keep this issue open until the progress tracker is gone!

**Comment by vkunniyur** [comment]
Hi sabeegrewal, can I give a HDFS directory location for the Progress Directory?

**Comment by sabeegrewal** [comment]
Hey @vkunniyur, please join the gitter chat if you can. That's the best place to ask these kinds of questions :) I'd like to keep the issues more focused. 

https://gitter.im/azure-event-hubs-spark/Lobby
