### ISSUE TITLE
Question: Distributed progress dir for Standalone Spark

### ISSUE THREAD

**Issue by ammills01** [Azure/azure-event-hubs-spark#210]
I've written several Spark Streaming jobs using this connector and I'm looking for a way to store the job progress in a central location.  I am running Spark Standalone on my own cluster (Azure VM's), so I don't have HDFS to rely on like I would if I were running it on YARN or HDInsights.  Currently, I am storing it on the local file system.  This mostly works until the job is being executed on a different node in the cluster, then progress is lost or behind.

I know with the .NET implementation of the receiver you can specify an Azure storage account but I've not found anything like that with this implementation.

I did attach a Shared Folder from an Azure Storage Account and try to use that but it blows up because the library tries to change permissions on the directory.

Any guidance here other than install HDFS?

Thanks in advance.

-- Andrew

**Comment by sabeegrewal** [comment]
Hey Andrew, Azure Storage should solve your problem. Could the issue be that you need to give your VM permissions from your Azure Storage account?

**Comment by ammills01** [comment]
Hey sabee, thanks for responding so quickly.  What I tried was mounting a shared File storage directory to each VM in the cluster (https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share).  I verified that I could read/write to the folder with root as well as the user that Spark is running as (gtadmin).  I then tried to submit the job to the Spark cluster and I get the following erorrs:

17/11/09 19:47:36 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
17/11/09 19:47:36 ERROR JobScheduler: Error running job streaming job 1510256791000 ms.0
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, 10.179.245.164, executor 0): ExitCodeException exitCode=1: chmod: changing permissions of ‘/spark/progress/SaveToCassandra_temp/0-onesykesdev-gtevents-ns-ingress-api-partition-0-1510256791000’: Operation not permitted

        at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
        at org.apache.hadoop.util.Shell.run(Shell.java:479)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
        at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:733)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:225)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
        at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:296)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.spark.eventhubscommon.progress.ProgressWriter.write(ProgressWriter.scala:49)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.retrieveDataFromPartition(EventHubsRDD.scala:123)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.compute(EventHubsRDD.scala:147)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:924)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:924)
        at com.sykes.spark.streamingJobs.SaveToCassandra$$anonfun$main$1.apply(SaveToCassandra.scala:51)
        at com.sykes.spark.streamingJobs.SaveToCassandra$$anonfun$main$1.apply(SaveToCassandra.scala:48)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
        at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:256)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:255)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: ExitCodeException exitCode=1: chmod: changing permissions of ‘/spark/progress/SaveToCassandra_temp/0-onesykesdev-gtevents-ns-ingress-api-partition-0-1510256791000’: Operation not permitted

        at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
        at org.apache.hadoop.util.Shell.run(Shell.java:479)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
        at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:733)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:225)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
        at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:296)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.spark.eventhubscommon.progress.ProgressWriter.write(ProgressWriter.scala:49)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.retrieveDataFromPartition(EventHubsRDD.scala:123)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.compute(EventHubsRDD.scala:147)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        ... 3 more
17/11/09 19:47:36 FATAL root: Method: SaveToCassandra; Message: Error: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, 10.179.245.164, executor 0): ExitCodeException exitCode=1: chmod: changing permissions of ‘/spark/progress/SaveToCassandra_temp/0-onesykesdev-gtevents-ns-ingress-api-partition-0-1510256791000’: Operation not permitted

        at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
        at org.apache.hadoop.util.Shell.run(Shell.java:479)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
        at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:733)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:225)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
        at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:296)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.spark.eventhubscommon.progress.ProgressWriter.write(ProgressWriter.scala:49)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.retrieveDataFromPartition(EventHubsRDD.scala:123)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.compute(EventHubsRDD.scala:147)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:; Stack Trace: [Ljava.lang.StackTraceElement;@455824ad

As far as I can tell it looks like the code that attempts to save progress is trying to run chmod on the folder, which it is not allowed to do to a share folder like I have attached.

**Comment by sabeegrewal** [comment]
Hey, no worries! Are you sure there's no way to allow `chmod` to be run on Azure File Shares?

Also, have you tried using Blob storage? You wouldn't need to mount it per VM in your cluster and it's hdfs-compatible.

**Comment by ammills01** [comment]
I think using blob storage would make this much simpler, similar to how the .NET library does it.  However, I was not able to find any examples that showed anything other than a local path for the progress directory.  Can you provide a code snippet as to how one might accomplish this?

In the mean time I'll look into allowing `chmod` on the file share.

**Comment by sabeegrewal** [comment]
`wasb[s]://<containername>@<accountname>.blob.core.windows.net/<path>`

Could you try that format with blob storage? You may need to import the hadoop-azure module though...I'm not sure if it comes with Hadoop out-of-the-box. If that works, I can add some info about it to our documentation. 

Also, as an aside, I'm currently re-writing major components of the library. Currently, I'm re-writing how user-configuration works and writing supporting documentation. After that, I will be phasing out the EventHubs-specific progress directory, so all checkpointing will be done by Spark. Once that's done, hopefully this type of setup will become much simpler. 👍

**Comment by ammills01** [comment]
Thanks!

Bummer on phasing out EH-specific progress directory, that's one of the things I liked most about this library... Spark's checkpointing kinda stinks in that it checkpoints the job code making changes more challenging.  I noticed some threading issues you guys are battling, and I'm seeing them when trying to run the jobs on the same executor.  Is that why you've decided to abandon it?

I had these jobs consuming a Kafka queue before swapping to EventHubs and implemented my own checkpointing solution there, saving offsets to Zookeeper.  Is that going to be the suggested route with this library going forward if you don't want to use Sparks checkpointing?

**Comment by sabeegrewal** [comment]
Sweet! Keep me posted!

Having a separate progress tracker is adding performance issues and unneeded complexity (and bugs) to the library which is why we've decided to remove it. Very low-latency jobs aren't possible at the moment. 

You're right that doing basic checkpointing with Spark tightly couples EventHubs progress with Spark's progress. That's a perfectly fine option to offer users, but I don't like that being the only option (same as you). With that said, I don't think our current solution is the right approach. Checkpointing in the EventHubs service will decouple EventHubs and Spark progress while still keeping this library performant, and I think that's the right move. I'm going to be pushing hard for service-side checkpointing, but I don't know when that will be done just yet. I also plan on allowing users to manage offsets on their own if they'd like to. 

I've started maintaining a roadmap in the wiki. It's lacking detail for sure, but that'll be the place I add more specifics when I have them.

**Comment by ammills01** [comment]
I appreciate the consistent and timely dialog sabee.  Just curious, do you all have a Slack channel you use for this sort of conversation or this the best place for it?

I certainly understand your point and agree that an approach which isolates specific tasks into individual libraries makes sense. It allows users the flexibility of picking and choosing the libraries they want instead of bloating a library they need with things they don't want to use.

We were planning on swapping from Kafka to Azure Event Hubs for our primary queue. Currently, this queue only moves a few million events per work day however we intend to be in the hundreds of millions if not just over a billion events per day. With that said, would you suggest I hold off on implementing this swap now given the state of flux this library is in?

I did see the roadmap wiki and I'm pretty excited about several of the changes you have listed. I appreciate the look forward and general time-frame.

As far as the progress tracking with Blob storage goes, it looks like it will work, I just need to familiarize myself with the Hadoop Azure library and how credentials work, which I'm working on now.

**Comment by sabeegrewal** [comment]
I'm relatively new to this library, and building a community is something I'm very interested in doing. I'll look into starting a slack/gitter, and I'll update the README when that's done. I think I lean towards gitter (though I don't care too much either way), so let me know if you have a preference. 

Also, I would continue with your swap if it's something you guys are gonna do. The breaking changes will be pretty minor. And, while they won't be released for a couple months, you can see them in `master` and there will be staging builds you can develop against. And, I'm always available to work with you during that process too.

**Comment by ammills01** [comment]
I don't have a preference, was only curious since 'chatting' in a bug report is foreign to me.

I'll discuss with my colleagues the pro's and con's of a the swap as it sits now. The price and performance of Azure Event Hubs is certainly appealing when compared to hardware cost and technical debt of hosting our own Kafka. However, Kafka is up and running for us right now and the library to integrate Spark Streaming and Kafka is much more mature.

Does this library have the ability to turn off internal progress tracking and allow me to track my own, similar to the Kafka library?

**Comment by sabeegrewal** [comment]
Ok, cool. Yea, it's foreign to me as well....the README will be updated soon with more on that. 👍 

We don't have support for that yet....that's what I meant with "I also plan on allowing users to manage offsets on their own if they'd like to". That's pretty straightforward to implement, and it's planned for right after the progress directory is phased out. I threw it up on the roadmap just now too. The final checkpointing method (service-side checkpointing) will come last.

**Comment by sabeegrewal** [comment]
Gitter is up! Feel free to move non-blob storage stuff there. :)

**Comment by sabeegrewal** [comment]
Hey Andrew, I going to close this for now. Feel free to re-open it (or create a new issue) when you come back to the library down the road :)
