### ISSUE TITLE
java.lang.AssertionError: assertion failed: DataFrame returned by getBatch from org.apache.spark.sql.streaming.eventhubs.EventHubsSource@3115caf3 did not have isStreaming=true

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-event-hubs-spark#213]
### Bug Report
- Actual behavior: assertion failure while running an Azure Databricks PySpark notebook streaming from Event Hub
- Expected behavior: streaming succeeds
- Spark version: Azure Databricks Runtime Version 3.4 (Scala 2.11)
- spark-eventhubs artifactId and version: spark-streaming-eventhubs_2.11-2.1.5.jar

The notebook runs a basic test:

```
stream = (spark.readStream
  .format("eventhubs")
  .option("eventhubs.policyname", "<snip>")
  .option("eventhubs.policykey", "<snip>")
  .option("eventhubs.namespace", "<snip>")
  .option("eventhubs.name", "<snip>")
  .option("eventhubs.partition.count", "16")
  .option("eventhubs.maxRate", "100")
  .option("eventhubs.consumergroup", "<snip>")
  .option("eventhubs.progressTrackingDir", "dbfs:/progress/<snip>")
  .option("eventhubs.sql.containsProperties", "true")
  .option("eventhubs.filter.enqueuetime", int(time.time()) - 600)
  .load())

query = (stream
    .writeStream
    .format("memory")
    .queryName("<snip>")
    .outputMode("append")
    .start())
```

This seems to be related to [this change](https://github.com/apache/spark/commit/3c0c2d09ca89c6b6247137823169db17847dfae3) in Spark that added an extra assert:

```
           val batch = source.getBatch(current, available)
           assert(batch.isStreaming,
             s"DataFrame returned by getBatch from $source did not have isStreaming=true\n" +
               s"${batch.queryExecution.logical}")
```

**Comment by sabeegrewal** [comment]
Hey Matthieu, can you try using the package azure-eventhubs-databricks_2.11:3.3? The assertion error is definitely handled there. We're working on getting an official package for Databricks 3.4 as well. 

Let me know how it goes!

**Comment by mmaitre314** [comment]
Changing the package helped a bit. The job went a bit further and failed on this exception. Unclear what could cause that.

```
17/11/27 21:58:05 ERROR Executor: Exception in task 1.0 in stage 1.0 (TID 17)
java.lang.ClassCastException: scala.collection.mutable.HashMap cannot be cast to org.apache.spark.sql.catalyst.util.MapData
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getMap(rows.scala:50)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getMap(rows.scala:194)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:405)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:249)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:243)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:828)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:828)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sabeegrewal** [comment]
```scala
val spark = SparkSession.builder().getOrCreate()
import spark.implicits._
val inputStream = spark.readStream
  .format("eventhubs") 
  // etc etc 
```

Try making your SparkSession like that! Also, I'm new to Databricks. Is there any easy way to use Scala libraries in PySpark? 

Also, I'd like to note that these are workarounds! We've been in the process of re-writing the library for a little over a month. Upcoming releases will work smoother and be better documented 👍

**Comment by mmaitre314** [comment]
I verified that the issue has been resolved in azure-eventhubs-databricks_2.11:3.4.0.
