### ISSUE TITLE
Read Event Hub data from latest offset

### ISSUE THREAD

**Issue by vkunniyur** [Azure/azure-event-hubs-spark#219]
Hi,
   I have a use case where I want to start reading the event-hub from the latest offset rather than from the beginning. It looks like the first time when I run my spark application by default   the EventHubDirectDStream starts reading from the beginning. 
How can I read from the latest offset when I submit my spark application for the first time. I tried to pass the parameter  "eventhubs.filter.offset"  with value "@latest"  but it gave the following error,

Exception in thread "main" java.lang.NumberFormatException: For input string: "@latest"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:589)
at java.lang.Long.parseLong(Long.java:631)
at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)at org.apache.spark.eventhubscommon.RateControlUtils$$anonfun$composeFromOffsetWithFilteringParams$1.apply(RateControlUtils.scala:150)
at org.apache.spark.eventhubscommon.RateControlUtils$$anonfun$composeFromOffsetWithFilteringParams$1.apply(RateControlUtils.scala:139)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at org.apache.spark.eventhubscommon.RateControlUtils$.composeFromOffsetWithFilteringParams(RateControlUtils.scala:139)at org.apache.spark.streaming.eventhubs.EventHubDirectDStream.composeOffsetRange(EventHubDirectDStream.scala:256)
at org.apache.spark.streaming.eventhubs.EventHubDirectDStream.proceedWithNonEmptyRDD(EventHubDirectDStream.scala:287)
at org.apache.spark.streaming.eventhubs.EventHubDirectDStream.compute(EventHubDirectDStream.scala:374)

**Comment by sabeegrewal** [comment]
Hey vkunniyur, there's not easy way to do that in the current version of the library. If you look at the open PR right now, we're revamping the library to allow for scenarios like this. I'm writing tests now, and will hopefully have a release in the next couple weeks.

**Comment by vkunniyur** [comment]
Hi sabeegrewal, thank you for your reply to my question. I would definitely like try out the staging version. where can i get that from? Also what would be an approximate time around which I can expect the release of the revamped library?

**Comment by sabeegrewal** [comment]
Hey @vkunniyur, we're hopping to release early in Q1 of 2018. You should join the gitter chat here: https://gitter.im/azure-event-hubs-spark/Lobby if you'd like to talk more! We can sort out a staging version for you and talk details about the connector. I think that would work much better than hopping across multiple issues :)

**Comment by sabeegrewal** [comment]
Marking as closed - the conversation has moved to gitter! 

https://gitter.im/azure-event-hubs-spark/Lobby
