### ISSUE TITLE
com.microsoft.azure.eventhubs.EventHubException: The supplied sequence number is larger than the last sequence number

### ISSUE THREAD

**Issue by tilumi** [Azure/azure-event-hubs-spark#315]
Hi, I use version 2.3.1

When I consume from (namespace: wascl-eop, name: wasclmonitors),  it shows the following error
```
18/05/07 10:00:37 WARN TaskSetManager: Lost task 35.0 in stage 0.0 (TID 29, wn0-lam-ag.ifckrjhhuanelgm1hrygboricd.xx.internal.cloudapp.net, executor 15): com.microsoft.azure.eventhubs.EventHubException: The supplied sequence number '1595675164' is invalid. The last sequence number in the system is '1968601' TrackingId:645f549c-17d2-42bf-bf7d-fe7eade88503_M3SN1_M3SN1_G4_B7, SystemTracker:wascl-eop:EventHub:wasclmonitors~4095|lam-agg-v2-testing, Timestamp:5/7/2018 10:00:36 AM Reference:86e07868-70d6-47e7-8c3e-2bf24c60e080, TrackingId:557fc002-b18a-4597-ae00-f56a1cee3004_B7, SystemTracker:wascl-eop:eventhub:wasclmonitors~4095|lam-agg-v2-testing, Timestamp:5/7/2018 10:00:36 AM TrackingId:04267fc4390f4af1a48e01412cf9dc3a_G0, SystemTracker:gateway7, Timestamp:5/7/2018 10:00:36 AM, errorContext[NS: wascl-eop.servicebus.windows.net, PATH: wasclmonitors/ConsumerGroups/lam-agg-v2-testing/Partitions/3, REFERENCE_ID: a717d6_dc3a_G0_1525687236625]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:41)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:606)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:50)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:36)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.impl.AmqpException: The supplied sequence number '1595675164' is invalid. The last sequence number in the system is '1968601' TrackingId:645f549c-17d2-42bf-bf7d-fe7eade88503_M3SN1_M3SN1_G4_B7, SystemTracker:wascl-eop:EventHub:wasclmonitors~4095|lam-agg-v2-testing, Timestamp:5/7/2018 10:00:36 AM Reference:86e07868-70d6-47e7-8c3e-2bf24c60e080, TrackingId:557fc002-b18a-4597-ae00-f56a1cee3004_B7, SystemTracker:wascl-eop:eventhub:wasclmonitors~4095|lam-agg-v2-testing, Timestamp:5/7/2018 10:00:36 AM TrackingId:04267fc4390f4af1a48e01412cf9dc3a_G0, SystemTracker:gateway7, Timestamp:5/7/2018 10:00:36 AM
	... 13 more
```
I consume from the end of stream:
![screenshot 2018-05-08 08 05 45](https://user-images.githubusercontent.com/734766/39730886-b7b3a670-5296-11e8-835e-799f84f6ef74.png)

**Comment by sabeegrewal** [comment]
Hey this should be handled in #306 - I'll be backporting those changes to spark-2.2 later this month.
