### ISSUE TITLE
java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.eventhubs.impl.MessageReceiver instance is Closed. error

### ISSUE THREAD

**Issue by vijayupadya** [Azure/azure-event-hubs-spark#362]
We are frequently hitting the below error when reading from the eventhub. We see this on both DataBricks and HDInsights.

Version: azure-eventhubs-spark_2.11-2.3.2

There are two kinds of errors I see in the same job that is failing, some tasks fail with callstack1 and others with callstack2.

==========================
**Callstack1:**

java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.eventhubs.impl.MessageReceiver instance is Closed.
	at com.microsoft.azure.eventhubs.impl.ClientEntity.throwIfClosed(ClientEntity.java:115)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.receive(MessageReceiver.java:250)
	at com.microsoft.azure.eventhubs.impl.PartitionReceiverImpl.receive(PartitionReceiverImpl.java:142)
	at com.microsoft.azure.eventhubs.PartitionReceiver.lambda$receiveSync$0(PartitionReceiver.java:89)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.sync(ExceptionUtil.java:179)
	at com.microsoft.azure.eventhubs.PartitionReceiver.receiveSync(PartitionReceiver.java:89)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.liftedTree1$1(CachedEventHubsReceiver.scala:103)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:102)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:157)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:147)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:128)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:620)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:620)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:49)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$1.apply(Collector.scala:118)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$1.apply(Collector.scala:117)
	at org.apache.spark.SparkContext$$anonfun$35.apply(SparkContext.scala:2222)
	at org.apache.spark.SparkContext$$anonfun$35.apply(SparkContext.scala:2222)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:111)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

==========================
**Callstack2:**
java.lang.IllegalStateException: No receiver for {"ehName":"test","partitionId":2}
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.receiver(CachedEventHubsReceiver.scala:90)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.liftedTree1$1(CachedEventHubsReceiver.scala:103)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:102)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:157)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:147)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD$EventHubsRDDIterator.next(EventHubsRDD.scala:128)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:620)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:620)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:49)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$1.apply(Collector.scala:118)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$1.apply(Collector.scala:117)
	at org.apache.spark.SparkContext$$anonfun$35.apply(SparkContext.scala:2222)
	at org.apache.spark.SparkContext$$anonfun$35.apply(SparkContext.scala:2222)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:111)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sabeegrewal** [comment]
Bundling this with #363 - these both are related. A closed connection is being read! I'm still investigating the issue.
