### ISSUE TITLE
json4s - MappingException - Can't find ScalaSig for class UnknownDescribedType

### ISSUE THREAD

**Issue by sabeegrewal** [Azure/azure-event-hubs-spark#372]
`UnknownDescribedType` should never make it to json4s. Currently it does which crashes the job.

**Comment by p2bauer** [comment]
I'm running into the same issue using the code built from the branch pending PR merge here: https://github.com/Azure/azure-event-hubs-spark/pull/373

Maybe it's something to do with how I'm building it? Or something else?  Was hoping @sabeegrewal  you would recognize something...

```org.json4s.package$MappingException: Can't find ScalaSig for class org.apache.qpid.proton.codec.DecoderImpl$UnknownDescribedType
	at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:42)
	at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:26)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:108)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:148)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:116)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:156)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.package$Memo.apply(package.scala:39)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:90)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:196)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.Extraction$.decompose(Extraction.scala:210)
	at org.json4s.jackson.Serialization$.write(Serialization.scala:22)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$11$$anonfun$apply$8$$anonfun$apply$10.apply(EventHubsSource.scala:336)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$11$$anonfun$apply$8$$anonfun$apply$10.apply(EventHubsSource.scala:335)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$11$$anonfun$apply$8.apply(EventHubsSource.scala:335)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$11$$anonfun$apply$8.apply(EventHubsSource.scala:306)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.foreach(WholeStageCodegenExec.scala:612)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2.scala:130)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2.scala:129)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2.scala:135)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$2.apply(WriteToDataSourceV2.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$2.apply(WriteToDataSourceV2.scala:78)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by p2bauer** [comment]
sbt file snippet:
``` "com.microsoft.azure"%"azure-eventhubs"%"1.0.2",
  "org.scala-lang.modules"%"scala-java8-compat_2.11"%"0.9.0",
  "com.microsoft.azure" % "azure-eventhubs-spark_2.11" % "2.3.3" from "https://__hostedlocation_built_from_sabees_fork___/azure-eventhubs-spark_2.11-2.3.3-SNAPSHOT.jar",```
