### ISSUE TITLE
AmqpException: The service was unable to process the request

### ISSUE THREAD

**Issue by SvetlanaPan** [Azure/azure-event-hubs-spark#374]
Unable to instanciate EventHub sender for EventHub.

Caused by: com.microsoft.azure.eventhubs.EventHubException: com.microsoft.azure.eventhubs.impl.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:a16b0a4dea5a4f55a3ea412950829118_G26, SystemTracker:gateway5, Timestamp:6/30/2018 2:42:39 AM
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:39)
	at com.microsoft.azure.eventhubs.impl.MessageSender.onClose(MessageSender.java:367)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:50)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:36)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462)

**Comment by sabeegrewal** [comment]
closing as duplication of #367 - I'm looking into it! Thanks for sharing the logs :) 

Please add any other updates to the other open issue!
