### ISSUE TITLE
EventHubException: Put token failed. status-code: 500

### ISSUE THREAD

**Issue by howardatwork** [Azure/azure-event-hubs-spark#383]
Using this version:
compile group: 'com.microsoft.azure', name: 'azure-eventhubs-spark_2.11', version: '2.3.1'
I'm getting the error below frequently in a streaming job using DStream API. With this exception, it will failed the job running on Databrick.

```
18/09/07 07:42:00 ERROR Uncaught throwable from user code: com.microsoft.azure.eventhubs.EventHubException: Put token failed. status-code: 500, status-description: Management operation failed. status-code: 500, status-description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101.
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.amqpResponseCodeToException(ExceptionUtil.java:76)
	at com.microsoft.azure.eventhubs.impl.ManagementChannel$1$1.onComplete(ManagementChannel.java:57)
	at com.microsoft.azure.eventhubs.impl.ManagementChannel$1$1.onComplete(ManagementChannel.java:46)
	at com.microsoft.azure.eventhubs.impl.RequestResponseChannel$ResponseHandler.onReceiveComplete(RequestResponseChannel.java:222)
	at com.microsoft.azure.eventhubs.impl.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:84)
```

**Comment by sabeegrewal** [comment]
Howard, please upgrade to `2.3.3` - reopen the issue if you still see problems!
