### ISSUE TITLE
Eventhub exception complains "new receiver with higher epoch of '0' than current epoch '0'"

### ISSUE THREAD

**Issue by fuzhouch** [Azure/azure-event-hubs-spark#388]
Bug Report:
I ta Spark streaming job on Azure Databricks (see version below) to read two Eventhub instances and union them to on stream. I found an exception happening on every mini-batch and causes a delay of 1+ minute.

- Actual behavior: An exception throws on every mini-batch on some partitions (randomly picked, not consistently happening on same partition). See batch below
- Expected behavior: There's no exception and all data get read.
- Spark version =  2.3.1 on Azure Databricks
- spark-eventhubs artifactId and version = com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.3

Exception stack:

```
java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:fad85c7f000102dc0001c47b5b97728f_G0_B1, SystemTracker:adseventhubdemo:eventhub:nad_ah_hub~21503|fuzhouch1, Timestamp:9/11/2018 7:45:58 AM, errorContext[NS: adseventhubdemo.servicebus.windows.net, PATH: nad_ah_hub/ConsumerGroups/fuzhouch1/Partitions/20, REFERENCE_ID: 3116e4_db74_G0_1536651909221, PREFETCH_COUNT: 4368, LINK_CREDIT: 4314, PREFETCH_Q_LEN: 0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:98)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.drainPendingReceives(MessageReceiver.java:439)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:425)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:658)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:50)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:36)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:fad85c7f000102dc0001c47b5b97728f_G0_B1, SystemTracker:adseventhubdemo:eventhub:nad_ah_hub~21503|fuzhouch1, Timestamp:9/11/2018 7:45:58 AM, errorContext[NS: adseventhubdemo.servicebus.windows.net, PATH: nad_ah_hub/ConsumerGroups/fuzhouch1/Partitions/20, REFERENCE_ID: 3116e4_db74_G0_1536651909221, PREFETCH_COUNT: 4368, LINK_CREDIT: 4314, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:657)
	... 11 more
```

**Comment by sabeegrewal** [comment]
Please read the [FAQ](https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md). If you have further questions, please raise them on the gitter chat :) 

Basically, each Spark application needs to be run in its own consumer group.

**Comment by sakthig** [comment]
@sabeegrewal when this error occurs .. my spark driver which is running in kubernetes does not seem to be terminating. Kindly suggest right course of action.

**Comment by sabeegrewal** [comment]
@sakthig I'm not sure I understand. The exception is thrown and the Spark application continues to retry continuously?

**Comment by sakthig** [comment]
the driver does no quit. it continues to hang after this error along with the executors.

**Comment by sabeegrewal** [comment]
Interesting. Last I checked, if an exception is thrown that Spark doesn't know how to handle (like this one!), then the exception will continue to bubble up and the application will eventually exit.

That said, I no longer work on this project so I don't know if that has changed. @sjkwak should be able to help you. I'd reply with which version number you're running and he can help you when he sees this.

**Comment by sakthig** [comment]
Sure thanks (y),. My spark version is 2.4.3 and azure-eventhubs-spark is of 2.3.10

**Comment by sabeegrewal** [comment]
Sure thing. First thing I can say is that you should move the latest version (see the README). It looks like the latest release includes a fix from the Java SDK related to re-connection failures. If that still doesn't work, reply here and @sjkwak can help you.

**Comment by sakthig** [comment]
ok. i have updated the lib version. will report back if issue occurs again.

**Comment by sakthig** [comment]
After updating to new lib... It is not crashing even if i intentionally run two jobs with same consumer groups.

**Comment by sakthig** [comment]
@sjkwak 

i encountered that error again.

this was the trace

```
Exception in thread "main" org.apache.spark.sql.streaming.StreamingQueryException: Job aborted due to stage failure: Task 1 in stage 248.0 failed 4 times, most recent failure: Lost task 1.3 in stage 248.0 (TID 25063, 10.48.2.81, executor 1): java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:5d0d04d100140a7d00800bf15d5ba8e7_G0_B17, SystemTracker:wiseevents:eventhub:connectedlogistics~32766|test_aggregation_trip_delayed, Timestamp:2019-08-20T08:01:54, errorContext[NS: wiseevents.servicebus.windows.net, PATH: connectedlogistics/ConsumerGroups/test_aggregation_trip_delayed/Partitions/1, REFERENCE_ID: LN_92afd8_1566288103683_923b_G0, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:104)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.drainPendingReceives(MessageReceiver.java:466)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:451)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:746)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:106)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:5d0d04d100140a7d00800bf15d5ba8e7_G0_B17, SystemTracker:wiseevents:eventhub:connectedlogistics~32766|test_aggregation_trip_delayed, Timestamp:2019-08-20T08:01:54, errorContext[NS: wiseevents.servicebus.windows.net, PATH: connectedlogistics/ConsumerGroups/test_aggregation_trip_delayed/Partitions/1, REFERENCE_ID: LN_92afd8_1566288103683_923b_G0, PREFETCH_COUNT: 500, LINK_CREDIT: 500, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:745)
	... 15 more

```

**Comment by lcmarques** [comment]
I have exactly the same issue. I do think this is not consumer group - partition related. Can we handle the exception for avoid stream crash. Like try, except: com.microsoft.azure.eventhubs.ReceiverDisconnectedException pass ? Does it make sense? This is getting a little critical

**Comment by ytaous** [comment]
I am getting the error message, using SDK 2.3.12. I don't think it's related to consumer group either. I'll open an new issue if the exception persists.
