### ISSUE TITLE
com.microsoft.azure.eventhubs.ReceiverDisconnectedException

### ISSUE THREAD

**Issue by tilumi** [Azure/azure-event-hubs-spark#392]
- Exception:
```
18/09/28 22:05:23 WARN TaskSetManager: Lost task 22.0 in stage 0.0 (TID 7, wn2-lam-ag.mgg4o4rskuyuhhequtmmqpfffc.xx.internal.cloudapp.net, executor 18): java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ac1f212000015d1000555c8b5baea59e_G18_B22, SystemTracker:wascl-eur:eventhub:wasclmonitors~23551|sparktestcg, Timestamp:9/28/2018 10:05:23 PM, errorContext[NS: wascl-eur.servicebus.windows.net, PATH: wasclmonitors/ConsumerGroups/sparktestcg/Partitions/22, REFERENCE_ID: 6f3637_487_G18_1538172308105, PREFETCH_COUNT: 29048, LINK_CREDIT: 28949, PREFETCH_Q_LEN: 0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:98)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.drainPendingReceives(MessageReceiver.java:439)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:425)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:658)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:50)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:70)
	at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:36)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ac1f212000015d1000555c8b5baea59e_G18_B22, SystemTracker:wascl-eur:eventhub:wasclmonitors~23551|sparktestcg, Timestamp:9/28/2018 10:05:23 PM, errorContext[NS: wascl-eur.servicebus.windows.net, PATH: wasclmonitors/ConsumerGroups/sparktestcg/Partitions/22, REFERENCE_ID: 6f3637_487_G18_1538172308105, PREFETCH_COUNT: 29048, LINK_CREDIT: 28949, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:657)
	... 11 more

```
- Spark version: Azure HDinsight Spark 2.2
- spark-eventhubs artifactId: azure-eventhubs-spark_2.11 and version: 2.2.4

**Comment by sabeegrewal** [comment]
Hey Lucas, read the second question in the [FAQ](https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md). In short, you must use a different consumer group for ever Spark application!
