### ISSUE TITLE
spark-submit works while livy request fails

### ISSUE THREAD

**Issue by GANdalf2357** [Azure/azure-event-hubs-spark#430]
Hi!

I have the following issue:

When I perform a spark submit of a spark structured streaming job which uses azure-event-hubs-spark as input in version 2.3.9, the job is working just fine.

When I perform a REST call to the liviy REST api of HDInsight with excactly the same parameters to submit the same spark job, I get the following exception:

`
Caused by: java.lang.IllegalStateException: {"ehName":"***","partitionId":0} doesn't have a fromSeqNo

        at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$7$$anonfun$8.apply(EventHubsSource.scala:268)

        at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$7$$anonfun$8.apply(EventHubsSource.scala:268)

        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)

        at scala.collection.AbstractMap.getOrElse(Map.scala:59)

        at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$7.apply(EventHubsSource.scala:268)

        at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$7.apply(EventHubsSource.scala:266)

        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)

        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)

        at scala.collection.AbstractTraversable.map(Traversable.scala:104)

        at org.apache.spark.sql.eventhubs.EventHubsSource.getBatch(EventHubsSource.scala:266)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$1$$anonfun$apply$9.apply(MicroBatchExecution.scala:394)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$1$$anonfun$apply$9.apply(MicroBatchExecution.scala:390)

        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)

        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)

        at scala.collection.Iterator$class.foreach(Iterator.scala:893)

        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)

        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)

        at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)

        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)

        at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$1.apply(MicroBatchExecution.scala:390)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$1.apply(MicroBatchExecution.scala:390)

        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)

        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:389)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:133)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)

        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)

        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121)

        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)

        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117)

        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)

        ... 1 more
`
Do you have a clue what might be the reason for this issue?

Thanks for your help!

**Comment by GANdalf2357** [comment]
Issue can be closed, I could resolve the problem.

If anyone has the same problem, this is the reason/solution:
The problem was, that I had created 2 Entities in EventHubs and then I changed the used entity but at the same time stilled used the same checkpoint location. This broke the checkpoint/client processing and it was not usable anymore. Even a deletion of the checkpoint location did not fix the problem, therefore I recreated my used Azure environment.
