### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/eventhubs/EventHubsConf

### ISSUE THREAD

**Issue by lecummins** [Azure/azure-event-hubs-spark#442]
I am getting the below error when I try to stream from Event Hub using Spark:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/eventhubs/EventHubsConf
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:42)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.eventhubs.EventHubsConf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

I am building the project using sbt, below are the contents of my build.sbt file. It builds fine but when I try to run the resulting jar with spark-submit it throws the error.

------------------------------------------------------------------------------------------------------------------------------
name := "EventHubStreaming"
version := "0.1"
scalaVersion := "2.11.8"

// https://mvnrepository.com/artifact/org.apache.spark/spark-core
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.2"

//https://mvnrepository.com/artifact/org.apache.spark/spark-streaming
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "2.3.2"

// https://mvnrepository.com/artifact/org.apache.spark/spark-sql
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.2"

// https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs-spark_2.11
libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.10"

// https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs
libraryDependencies += "com.microsoft.azure" % "azure-eventhubs" % "2.3.0"

------------------------------------------------------------------------------------------------------------------------------

I have also tried using Scala version 2.11.12. Can anyone see what I am doing wrong?

**Comment by lecummins** [comment]
I figured out the issue - I'm very new to Scala and sbt and I didn't realise that the dependencies weren't automatically packaged with the built code. I used sbt assembly to package it all and I copied it to the cluster, the error is gone now.
