### ISSUE TITLE
Input byte array has wrong 4-byte ending unit

### ISSUE THREAD

**Issue by sanket-t-shah** [Azure/azure-event-hubs-spark#510]
Am trying to connect C# and use Spark.NET for reading from Event Hubs. For the same, I've followed the steps and code snippet given at https://github.com/dotnet/spark/issues/325 / https://gist.github.com/joperezr/de0c963213c69b870f2e65b92c5406a4.

While I try to do so, am able to compile C# code. When I run it, am getting error ```java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit```

Here is additional information that may help:

I copied following 3 files to spark --> jars folder.  
```azure-eventhubs-3.1.1.jar```  
```azure-eventhubs-spark_2.11-2.3.15.jar```  
```microsoft-spark-2.4.x-0.11.0.jar```  

Post copying of files, I executed command to run .NET Core Application:  
```spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local[*] microsoft-spark-2.4.x-0.11.0.jar IotHubConsumer.exe```  

My versions:  
```
E:\self-training\spark\IotHubConsumer\bin\Debug\netcoreapp3.1>spark-shell --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.5
      /_/

Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_202
Branch HEAD
Compiled by user centos on 2020-02-02T19:38:06Z
Revision cee4ecbb16917fa85f02c635925e2687400aa56b
Url https://gitbox.apache.org/repos/asf/spark.git
Type --help for more information.

E:\self-training\spark\IotHubConsumer\bin\Debug\netcoreapp3.1>java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

E:\self-training\spark\IotHubConsumer\bin\Debug\netcoreapp3.1>dotnet --version
3.1.202

```
Error Stack Trace:  
```

E:\self-training\spark\IotHubConsumer\bin\Debug\netcoreapp3.1>spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local[*] microsoft-spark-2.4.x-0.11.0.jar IotHubConsumer.exe
20/05/13 16:37:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2020-05-13T11:07:17.2027957Z] [SANKETSHAH-HP] [Info] [ConfigurationService] Using port 34401 for connection.
[2020-05-13T11:07:17.2157641Z] [SANKETSHAH-HP] [Info] [JvmBridge] JvMBridge port is 34401
20/05/13 16:37:24 ERROR MicroBatchExecution: Query [id = 73ea0a6c-6cb5-41e9-921f-d6fdb177eaca, runId = d9694079-294a-42e3-a531-5b30bbe1cf3b] terminated with error
java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
        at java.util.Base64$Decoder.decode0(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at org.apache.spark.eventhubs.EventHubsUtils$.decrypt(EventHubsUtils.scala:158)
        at org.apache.spark.eventhubs.EventHubsConf$.toConf(EventHubsConf.scala:553)
        at org.apache.spark.sql.eventhubs.EventHubsSource.<init>(EventHubsSource.scala:77)
        at org.apache.spark.sql.eventhubs.EventHubsSourceProvider.createSource(EventHubsSourceProvider.scala:82)
        at org.apache.spark.sql.execution.datasources.DataSource.createSource(DataSource.scala:255)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1$$anonfun$applyOrElse$1.apply(MicroBatchExecution.scala:88)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1$$anonfun$applyOrElse$1.apply(MicroBatchExecution.scala:85)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1.applyOrElse(MicroBatchExecution.scala:85)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1.applyOrElse(MicroBatchExecution.scala:83)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:257)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:247)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.logicalPlan$lzycompute(MicroBatchExecution.scala:83)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.logicalPlan(MicroBatchExecution.scala:65)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:269)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
20/05/13 16:37:24 ERROR DotnetBackendHandler: Failed to execute 'awaitTermination' on 'org.apache.spark.sql.execution.streaming.StreamingQueryWrapper' with args=()
[2020-05-13T11:07:24.4102208Z] [SANKETSHAH-HP] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'awaitTermination' failed for class '15' when called with no arguments
[2020-05-13T11:07:24.4103844Z] [SANKETSHAH-HP] [Error] [JvmBridge] org.apache.spark.sql.streaming.StreamingQueryException: Input byte array has wrong 4-byte ending unit
=== Streaming Query ===
Identifier: [id = 73ea0a6c-6cb5-41e9-921f-d6fdb177eaca, runId = d9694079-294a-42e3-a531-5b30bbe1cf3b]
Current Committed Offsets: {}
Current Available Offsets: {}

Current State: INITIALIZING
Thread State: RUNNABLE
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:297)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
        at java.util.Base64$Decoder.decode0(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at org.apache.spark.eventhubs.EventHubsUtils$.decrypt(EventHubsUtils.scala:158)
        at org.apache.spark.eventhubs.EventHubsConf$.toConf(EventHubsConf.scala:553)
        at org.apache.spark.sql.eventhubs.EventHubsSource.<init>(EventHubsSource.scala:77)
        at org.apache.spark.sql.eventhubs.EventHubsSourceProvider.createSource(EventHubsSourceProvider.scala:82)
        at org.apache.spark.sql.execution.datasources.DataSource.createSource(DataSource.scala:255)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1$$anonfun$applyOrElse$1.apply(MicroBatchExecution.scala:88)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1$$anonfun$applyOrElse$1.apply(MicroBatchExecution.scala:85)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1.applyOrElse(MicroBatchExecution.scala:85)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$1.applyOrElse(MicroBatchExecution.scala:83)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:257)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:247)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.logicalPlan$lzycompute(MicroBatchExecution.scala:83)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.logicalPlan(MicroBatchExecution.scala:65)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:269)
        ... 1 more

[2020-05-13T11:07:24.4458731Z] [SANKETSHAH-HP] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'awaitTermination' failed for class '15' when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method 'awaitTermination' failed for class '15' when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object[] args)
   at Microsoft.Spark.Sql.Streaming.StreamingQuery.AwaitTermination()
   at IotHubConsumer.Program.Main(String[] args) in E:\self-training\spark\IotHubConsumer\Program.cs:line 88

E:\self-training\spark\IotHubConsumer\bin\Debug\netcoreapp3.1>
```

**Comment by sjkwak** [comment]
Hi @sanket-t-shah - it looks connection string wasn't encrypted when it was added to the eventhub-conf. How was the eventhub-conf set up in Spark.NET env?

**Comment by sanket-t-shah** [comment]
Yes - it was not encrypted. Am not sure how to achieve it, as when I was doing the same in Scala, it was not encrypted there too.

Here is my code:
```
using Microsoft.Spark.Sql;
using Microsoft.Spark.Sql.Streaming;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using static Microsoft.Spark.Sql.Functions;

namespace IotHubConsumer
{
    public class EventHubPosition
    {
        public string Offset { get; set; }
        public long SeqNo { get; set; }
        public string EnqueuedTime { get; set; }
        public bool IsInclusive { get; set; }
    }

    public class PositionKey
    {
        [JsonPropertyName("ehName")]
        public string EventHubName { get; set; }
        [JsonPropertyName("partitionId")]
        public int PartitionId { get; set; }
    }

    public static class EventHubConnection
    {
        // When you call this method you will pass in here the number of partitions that your EventHub has.
        public static Dictionary<string, string> GetEventHubConnectionSettings()
        {
            // Change this for the name of your EventHub
            string eventHubName = "ocp-sku-2-iot-hub-dev";

            var eventHubStartingPosition = new EventHubPosition
            {
                Offset = "@latest",
                SeqNo = -1,
                IsInclusive = false
            };

            var startingPositions = new Dictionary<string, EventHubPosition>();

            for (int i = 0; i < 5; i++)
            {
                startingPositions.Add(JsonSerializer.Serialize(new PositionKey { EventHubName = eventHubName, PartitionId = i }),
                                      eventHubStartingPosition);
            }

            JsonSerializerOptions options = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            };

            return new Dictionary<string, string>
            {
                {"eventhubs.connectionString", "Endpoint=sb://iothub-ns-ocp-sku-2-2853203-b296062435.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=D7OMwUNyM47NmjRbVP583L8gjHdbq0qr31o265Y/PM0=;EntityPath=ocp-sku-2-iot-hub-dev" },
                {"eventhubs.consumerGroup", "databricks-sanket-cg" },
                {"eventhubs.startingPositions", JsonSerializer.Serialize(startingPositions, options) }
            };
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            SparkSession spark = SparkSession
                            .Builder()
                            .AppName("VS Telemetry processing using Spark.NET")
                            .GetOrCreate();

            DataFrame events = spark
                .ReadStream()
                .Format("eventhubs")
                .Option("eventhubs.connectionString", "Endpoint=sb://iothub-ns-ocp-sku-2-2853203-b296062435.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=D7OMwUNyM47NmjRbVP583L8gjHdbq0qr31o265Y/PM0=;EntityPath=ocp-sku-2-iot-hub-dev")
                .Load();

            Func<Column, Column> ToMessageAsString = Microsoft.Spark.Sql.Functions.Udf<byte[], string>((arg) =>
            {
                var message = Encoding.UTF8.GetString(arg);

                //actual UDF logic to go here
                return message;
            });

            // EventData Body has the payload
            events
                          .Select(ToMessageAsString(Microsoft.Spark.Sql.Functions.Col("Body")))
                          .CreateOrReplaceTempView("sanket");


            //events
            //    .Select()
            //    .CreateOrReplaceTempView("Messages");

            StreamingQuery query = spark
                .Sql("SELECT * FROM sanket")
                .WriteStream()
                .OutputMode("append")
                .Format("console")
                .Start();

            query.AwaitTermination();
        }
    }
}

```

**Comment by sjkwak** [comment]
Have you tried calling the org.apache.spark.eventhubs.EventHubsUtils.encrypt(..) API to encrypt it?

**Comment by sanket-t-shah** [comment]
Am not sure how to call it in C#. Can you please give some example?

**Comment by sjkwak** [comment]
I'm not familiar with Spark.NET. You'd need to ask it in the Spark.NET forum.

**Comment by sanket-t-shah** [comment]
@sjkwak - can you please give me sample of Java / Scala? I was able to use bare connection string like I used in C# successfully.

**Comment by sanket-t-shah** [comment]
I had to revert back to older version as Encryption function is still not available in C#. Closing this issue for now.

**Comment by moredatapls** [comment]
@sanket-t-shah You call the function by using the Interop layer of .NET for Spark.

```cs
using Microsoft.Spark.Interop; 

namespace Utils
{
    public static class ConnectionStringUtils
    {
        private static string EncryptConnectionString(string connectionString)
        {
            var jvm = SparkEnvironment.JvmBridge;

            var obj = jvm.CallStaticJavaMethod("org.apache.spark.eventhubs.EventHubsUtils", "encrypt", connectionString);

            return obj as string;
        }
    }
}
```

You have to add the following to your .csproj to get this to work. You can use the `IgnoresAccessChecksToGenerator` to get access to the internal methods of Microsoft.Spark.

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
  
    <!-- Configures the IgnoresAccessChecksToGenerator, allows you to access internal methods of Microsoft.Spark -->
    <PropertyGroup>
      <InternalsAssemblyNames>Microsoft.Spark</InternalsAssemblyNames>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="IgnoresAccessChecksToGenerator" Version="0.4.0" PrivateAssets="All" />
      <PackageReference Include="Microsoft.Spark" Version="0.11.0" />
    </ItemGroup>

</Project>
```

I know, it's a little hacky, but it works for me.
