### ISSUE TITLE
java.lang.UnsupportedOperationException: A link to connection '2774680' $management node has already been opened.

### ISSUE THREAD

**Issue by HarryUlysses** [Azure/azure-event-hubs-spark#534]
We got the following error message when connecting Azure Databricks to Eventhub:

Caused by: java.lang.UnsupportedOperationException: A link to connection '2774680' $management node has already been opened.
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:57)
	at com.microsoft.azure.eventhubs.impl.SendLinkHandler.onLinkFinal(SendLinkHandler.java:80)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:182)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:620)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Feature Requests: 

- What issue are you trying to solve?  Find the RCA and provide solution to prevent it
- How do you want to solve it? 
- What is your use case for this feature? 

Bug Report:

- Actual behavior: got the connection error message.
- Expected behavior: did not get this error message
- Spark version: Spark 2.4.5
- spark-eventhubs artifactId and version: com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.16

**Comment by nyaghma** [comment]
@HarryUlysses Do you have access to the driver/executor nodes logs? If yes, can you share those with us?

**Comment by nyaghma** [comment]
@HarryUlysses Do you see any other errors happening around the same time when the issue occurred?

**Comment by HarryUlysses** [comment]
Hi, please allow me some time. I will get back to you the logs

**Comment by HarryUlysses** [comment]
@nyaghma The issue happened at 4.00 am 8.22. Since it has been a long time and the cluster has been restarted, we could not receive the logs at that time. But I could observe that there were many **Driver is up but is not responsive, likely due to GC** on the cluster Event Log when the issue happened

**Comment by nyaghma** [comment]
Thanks for checking @HarryUlysses. Did the issue happen just once or multiple times?

**Comment by HarryUlysses** [comment]
@nyaghma I observed that it only happened twice on the cluster according to the same error message. The first one is 3.14 am utc+8, 8.22, the second one is 5.01 am utc+8, 8.22. When the two issues happened, both the cluster load was extremely high.

**Comment by HarryUlysses** [comment]
@nyaghma Please feel free to let me know if you need other details.

**Comment by HarryUlysses** [comment]
@nyaghma Do we have any update?

**Comment by nyaghma** [comment]
@HarryUlysses I haven't been able to repro the issue yet. Did you face the issue again? If yes, can share under what setup/circumstances?

**Comment by nyaghma** [comment]
@HarryUlysses We have been able to repro this issue and working on fixing it. The error is a transient error from the underlying java sdk and we are planning to include the fix in the next release.

**Comment by nyaghma** [comment]
The fix is included in version 2.3.18.

**Comment by bensalem22** [comment]
we're also experiencing the same issue again now
