### ISSUE TITLE
Key not found exception  at EventHubsSource.scala:298

### ISSUE THREAD

**Issue by tilumi** [Azure/azure-event-hubs-spark#571]
Bug Report:

version:
com.microsoft.azure: azure-eventhubs-spark_2.11:2.3.18

Exception:
```
2020-12-07 17:47:11 ERROR MicroBatchExecution:91  - Query nam06#audit [id = a35829ef-8760-4637-8266-88c0b2bf0c44, runId = e52be564-cb7e-454b-b64f-6a35fe114019] terminated with error
java.util.NoSuchElementException: key not found: {"ehName":"auditraw","partitionId":22}
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$rateLimit$1$$anonfun$apply$1.apply$mcJJ$sp(EventHubsSource.scala:298)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$rateLimit$1$$anonfun$apply$1.apply(EventHubsSource.scala:294)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$rateLimit$1$$anonfun$apply$1.apply(EventHubsSource.scala:294)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$rateLimit$1.apply(EventHubsSource.scala:294)
	at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$rateLimit$1.apply(EventHubsSource.scala:290)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.eventhubs.EventHubsSource.rateLimit(EventHubsSource.scala:290)
	at org.apache.spark.sql.eventhubs.EventHubsSource.getOffset(EventHubsSource.scala:237)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5$$anonfun$apply$9.apply(MicroBatchExecution.scala:345)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5$$anonfun$apply$9.apply(MicroBatchExecution.scala:345)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5.apply(MicroBatchExecution.scala:344)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5.apply(MicroBatchExecution.scala:341)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply$mcZ$sp(MicroBatchExecution.scala:341)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.withProgressLocked(MicroBatchExecution.scala:557)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:183)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
2020-12-07 17:47:11 DEBUG EventHubsSource:58  - Slow partition adjustment is on, cleaning up the partition performance tracker before stopping.
2020-12-07 17:47:11 DEBUG MicroBatchExecution:58  - Starting Trigger Calculation
2020-12-07 17:47:11 ERROR LoggingUtils$:26  - Application{forest=nam06, dataType=PpeDataSideliner, appName=PpeDataSideliner, version=1.0} failed
org.apache.spark.sql.streaming.StreamingQueryException: key not found: {"ehName":"auditraw","partitionId":22}
```

**Comment by mainaksarcar** [comment]
@nyaghma Do you have an idea which this fix will be released ? Is the slowPartitionAdjustment feature ready to be used in production.

Is there any workaround to avoid this exception? Currently our Spark application crashes multiple times and then just keeps running in the third or fourth attempt.

**Comment by achistef** [comment]
I've come across the same issue. We too have multiple streaming queries targeting multiple EventHubs running on a single Databricks cluster.

**Comment by williamdphillips** [comment]
We see this same issue when using Overwatch (https://github.com/databrickslabs/overwatch). We haven't yet found a workaround but will be reaching out toe MSFT support on the issue.

EDIT:
Our issue was a configuration problem with Overwatch (https://github.com/databrickslabs/overwatch) where we had specified the same workspace id multiple times which effectively caused concurrent queries for the same eventhub. Once the concurrent queries for the same workspace were resolved, the issue went away.
