### ISSUE TITLE
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed

### ISSUE THREAD

**Issue by AmanPandey123** [Azure/azure-event-hubs-spark#612]
Hi , 

We have pyspark code fetching data from single consumer group with multiple partitions from different event Hub instances under same Event Hub namespace . The jobs run 24*7 without any downtime expected . iterating in loop for every 15 minutes and pulling data and writing to ADLS Gen 1 Sink. 
recently after upgrading to 

Databricks Runtime 8.3 , Scala 2.12 , Spark 3.1.1  and 
event hub library version -  azure-eventhubs-spark_2.12:2.3.20
 the jobs ran fine without any issues for the first 8-9 days , but now we are seeing failed instances with error as below
 
An error occurred while calling o2180548.count. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 11 in stage 157672.0 failed 4 times, most recent failure: Lost task 11.3 in stage 157672.0 (TID 1205598) (10.139.64.6 executor 3312): java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed. at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) at java.util.concurrent.Com Command Line: 72

After restarting the cluster the issue was gone . I am afraid , i might encounter the issue again . What is the cause for this issue ?

**Comment by jdbree** [comment]
We have the same issue with our pyspark code, see my comment to issue #363. 

Databricks Runtime 8.4
Library versions:
- com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21
- com.microsoft.azure:azure-eventhubs:3.3.0

The error message:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 3350.0 failed 1 times, most recent failure: Lost task 1.1 in stage 3350.0 (TID 7401) (10.139.64.4 executor driver): java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.

and further down:

Caused by: java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
...

**Comment by dhamacher** [comment]
Hi,

we are getting the same error. 

**Cluster Config**:
* com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21 (maven)
* azure_eventhub (pypy)
* Databricks Runtime: 8.2

**Comment by jdbree** [comment]
@nyaghma I have sent you an email with the full logs.

**Comment by nyaghma** [comment]
@jdbree Thanks for sharing the log with me. The logs indicate that the issue in your case happened when a receiving task got preempted by the scheduler, which resulted in closing the ReactorDispatcher object used by the connector. After that retrying the task resulted in aborting the job due to the closed ReactorDispatcher object. 
We'll work on fixing the issue and make the connector resilient against task preemption. Meanwhile, to mitigate the issue I suggest adjusting the configs to prevent task preemptions. Specifically, in the logs I noticed the max parallelism is set to 4, which seems low for running multiple streams. Increasing the number of parallel tasks should help to prevent task preemptions.

**Comment by susheelvadde** [comment]
@nyaghma is max parallelism refer to the threadPool Size in EventHubConf or databricks related configuration?
