### ISSUE TITLE
Structured streaming fails for timeout on ClientConnection Pool

### ISSUE THREAD

**Issue by alexz00** [Azure/azure-event-hubs-spark#631]
Hi,
we are getting a timeout error when trying to open a Spark structured streaming query reading data from Azure Event Hub. The stack trace is:

> Caused by: java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]
> 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
> 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
> 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
> 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
> 	at scala.concurrent.Await$.result(package.scala:146)
> 	at org.apache.spark.eventhubs.client.ClientConnectionPool.org$apache$spark$eventhubs$client$ClientConnectionPool$$borrowClient(ClientConnectionPool.scala:92)
> 	at org.apache.spark.eventhubs.client.ClientConnectionPool$.borrowClient(ClientConnectionPool.scala:170)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.client(EventHubsClient.scala:62)
>      ....

We also see the following errors in the logs:

> 22/04/11 13:49:48 WARN MessagingFactory: messagingFactory[MF_a50464_1649684868691], hostName[myhub.servicebus.windows.net], message[Processing all pending tasks and closing old reactor.]
> 22/04/11 13:49:48 INFO ReactorHandler: name[MF_a50464_1649684868691] reactor.onReactorFinal
> 22/04/11 13:49:48 WARN ConnectionHandler: onTransportError hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
> 22/04/11 13:49:48 WARN MessagingFactory: onConnectionError messagingFactory[MF_7b1d4b_1649684928711], hostname[myhub.servicebus.windows.net], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
> 22/04/11 13:49:48 WARN MessagingFactory: onConnectionError messagingFactory[MF_7b1d4b_1649684928711], hostname[myhub.servicebus.windows.net], open hasn't complete, stopping the reactor
> 22/04/11 13:49:48 INFO ConnectionHandler: onConnectionUnbound hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], state[CLOSED], remoteState[UNINITIALIZED]
> 22/04/11 13:49:48 INFO ConnectionHandler: onConnectionFinal hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], **errorCondition[amqp:resource-limit-exceeded], errorDescription[local-idle-timeout expired]**
> 22/04/11 13:49:48 INFO RetryUtils: (TID -1) retrying createFromConnectionString after 10 ms
> 22/04/11 13:49:48 WARN MessagingFactory: messagingFactory[MF_7b1d4b_1649684928711], hostName[myhub.servicebus.windows.net], message[stopping the reactor because thread was interrupted or the reactor has no more events to process.]

We are using version azure-eventhubs-spark_2.12 version 2.3.21, with Spark 3.1.2

I've noted this issue (https://github.com/Azure/azure-event-hubs-spark/issues/582) but it doesn't seem the same since the error is on a different method.

Can you please help on this?

Thanks.

**Comment by vbakayov93** [comment]
I have the same issue @alexz00 Were you able to go past that?
